export type { DailyLog, WeeklyLog, Settings } from "./types";
export type {
  DailyLogInput,
  DailyLogUpdate,
  SettingsInput,
  SettingsUpdate,
} from "./types";

import type { DailyLog, WeeklyLog, Settings } from "./types";

export const mockSettings: Settings = {
  coachName: "쏘마데모코치",
  height: 163,
  currentWeight: 64.0,
  gender: "여성",
  dietStartDate: "2026-01-01",
  startWeight: 70,
  targetWeight: 59,
  dietPreset: "custom",
  targetMonths: 8,
  waterGoal: 2.2,
  routineWeightTime: "아침 기상 직후",
  routineExtra: [],
  intensiveDayOn: true,
  intensiveDayCriteria: "역대최저",
  coachStylePreset: "balanced",
  coachStyleExtra: [],
  onboardingComplete: true,
  lastNoticeSeenAt: null,
};

export const mockDailyLogs: DailyLog[] = [
  {
    date: "2026-04-07",
    day: 97,
    weight: 64.0,
    avgWeight3d: 64.5,
    weightChange: -6.0,
    water: null,
    exercise: null,
    breakfast: null,
    lunch: null,
    dinner: null,
    lateSnack: null,
    note: "오늘도 화이팅. 목표까지 5.0kg 남았어",
    closed: false,
    intensiveDay: true,
    feedback: "어제 64.5kg에서 오늘 64.0kg. 주말에 올랐던 거 하루 만에 다시 내렸어. 좋은 흐름이야. 오늘도 수분 잘 챙기고 저녁까지 관리하면 내일 새 최저 노릴 수 있어.",
    dailySummary: null,
    oneLiner: null,
  },
  {
    date: "2026-04-06",
    day: 96,
    weight: 64.5,
    avgWeight3d: 64.6,
    weightChange: -5.5,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: null,
    dinner: null,
    lateSnack: "N",
    note: null,
    closed: false,
    intensiveDay: true,
    feedback: null,
    dailySummary: null,
    oneLiner: null,
  },
  {
    date: "2026-04-05",
    day: 95,
    weight: 65.0,
    avgWeight3d: 64.4,
    weightChange: -5.0,
    water: 1.3,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "주말 외식 - 파스타 + 와인 한 잔",
    dinner: "고칼로리 외식",
    lateSnack: "Y",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일마다 반복되는 패턴이야. 외식 두 끼에 야식까지 65.0kg으로 올라왔어. 금요일 역대 최저 63.8kg이었는데 이틀 만에 1.2kg 올랐어. 주말이 항상 발목을 잡고 있어. 월요일 회복이 중요해.",
    oneLiner: "주말 외식+야식으로 반등. 월요일 회복이 관건.",
  },
  {
    date: "2026-04-04",
    day: 94,
    weight: 64.3,
    avgWeight3d: 64.0,
    weightChange: -5.7,
    water: 1.5,
    exercise: "N",
    breakfast: "그릭요거트 + 견과류 한 줌 + 블루베리",
    lunch: "가족 외식 - 칼국수",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일에도 역대 최저에서 이탈했어. 점심 외식 한 끼는 나쁘지 않은데 수분 1.5L는 많이 부족해. 운동 없이 주말이 흘러가고 있어. 내일 일요일에 야식만 참으면 월요일 복구 속도가 달라져.",
    oneLiner: "토요일 소식했지만 수분 부족. 내일 야식 절대 참기.",
  },
  {
    date: "2026-04-03",
    day: 93,
    weight: 63.8,
    avgWeight3d: 64.0,
    weightChange: -6.2,
    water: 2.8,
    exercise: "Y",
    breakfast: "현미밥 + 닭가슴살 100g + 시금치무침",
    lunch: "기념으로 맛있게 소식 - 비빔밥",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "63.8kg 역대 최저! 3개월 만에 가장 낮은 숫자야. 운동, 수분, 야식 없음 완벽하게 맞췄어. 이 흐름을 주말까지 이어가는 게 숙제야. 주말이 항상 변수였으니까.",
    oneLiner: "역대 최저 63.8kg 경신. 주말 관리가 다음 목표.",
  },
  {
    date: "2026-04-02",
    day: 92,
    weight: 64.0,
    avgWeight3d: 64.3,
    weightChange: -6.0,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부구이 + 나물 반찬",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.0kg, 역대 최저 타이. 목요일도 안정적으로 내려가고 있어. 수분 2.5L는 목표에서 0.3L 부족하지만 전반적으로 잘 했어. 내일 63.8 아래 진입 노려볼 수 있어.",
    oneLiner: "64.0kg 역대 최저 타이. 내일 신기록 노려볼 것.",
  },
  {
    date: "2026-04-01",
    day: 91,
    weight: 64.3,
    avgWeight3d: 64.7,
    weightChange: -5.7,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "4월 첫날 64.2kg으로 잘 시작했어. 3월 마지막 주 주말에 올랐다가 이틀 만에 회복했어. 운동, 식단, 수분 모두 무난하게 챙겼어. 이번 주도 이 흐름 유지해.",
    oneLiner: "4월 첫날 64.2kg. 주말 반등 빠르게 회복 중.",
  },
  {
    date: "2026-03-31",
    day: 90,
    weight: 64.7,
    avgWeight3d: 64.6,
    weightChange: -5.3,
    water: 2.8,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 한 줌",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 닭가슴살 + 채소볶음",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등을 화요일에 잡기 시작했어. 64.5kg, 수분 2.8L에 운동까지 챙겼어. 주말 65.0kg에서 이틀 만에 0.5kg 내려왔어. 이 속도면 내일 64.0 돌파 가능해.",
    oneLiner: "주말 반등 회복 중. 내일 64.0 진입 목표.",
  },
  {
    date: "2026-03-30",
    day: 89,
    weight: 65.0,
    avgWeight3d: 64.6,
    weightChange: -5.0,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "월요일 64.9kg으로 주말 피해 복구 시작. 세 끼 모두 잘 챙겼고 운동도 했어. 수분 2.5L는 목표보다 조금 부족하지만 전반적으로 깔끔한 하루야. 내일도 이 루틴 이어가면 역대 최저 금방 다시 찍어.",
    oneLiner: "월요일 즉각 복구 시작. 역대 최저 재진입 눈앞.",
  },
  {
    date: "2026-03-29",
    day: 88,
    weight: 64.2,
    avgWeight3d: 64.4,
    weightChange: -5.8,
    water: 1.5,
    exercise: "N",
    breakfast: "늦잠 자서 브런치로 때움",
    lunch: "친구들이랑 삼겹살 + 냉면",
    dinner: "2차 포차에서 안주+소주",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일에 65.2kg으로 반등했어. 친구 약속으로 1차 삼겹살, 2차 포차까지 갔어. 야식은 참은 게 그나마 다행이야. 수분 1.5L는 목표의 68%밖에 안 돼. 내일 월요일 즉각 복구 모드.",
    oneLiner: "일요일 약속으로 반등. 그래도 야식 참은 건 잘 했어.",
  },
  {
    date: "2026-03-28",
    day: 87,
    weight: 64.7,
    avgWeight3d: 64.2,
    weightChange: -5.3,
    water: 1.8,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 일식 정식",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "역대 최저 다음날 토요일 64.5kg으로 소폭 반등. 외식 한 끼는 괜찮아, 운동 없는 게 좀 아쉽긴 해. 야식 참은 건 잘 했어. 일요일에 약속이 있으면 더 조심해야 해.",
    oneLiner: "역대 최저 다음날 소폭 반등. 일요일 관리가 관건.",
  },
  {
    date: "2026-03-27",
    day: 86,
    weight: 64.2,
    avgWeight3d: 64.0,
    weightChange: -5.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 블루베리 + 견과류",
    lunch: "현미밥 + 두부구이 + 나물",
    dinner: "관리식단",
    lateSnack: "N",
    note: "64.0kg 역대 최저!! 이 맛에 다이어트 하지",
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.0kg 역대 최저 경신! 1월 1일 70.0kg에서 3개월 만에 6.0kg을 뺐어. 운동, 식단, 수분 모두 완벽하게 맞춘 결과야. 이 흐름 주말에도 이어가면 63kg 초반 진입 금방이야.",
    oneLiner: "64.0kg 역대 최저 경신! 3개월 6.0kg 감량 달성.",
  },
  {
    date: "2026-03-26",
    day: 85,
    weight: 63.7,
    avgWeight3d: 64.2,
    weightChange: -6.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.2kg, 역대 최저 64.3kg 갱신! 드디어 63kg 중반대 진입했어. 운동도 하고 야식도 참고 잘 했어. 내일 64.0 진입할 수 있어.",
    oneLiner: "64.2kg 역대 최저 경신. 내일 66.5 노려봐.",
  },
  {
    date: "2026-03-25",
    day: 84,
    weight: 64.2,
    avgWeight3d: 64.6,
    weightChange: -5.8,
    water: 2.8,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 닭가슴살 + 시금치무침",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "64.5kg, 안정적으로 내려가는 중이야. 수분 2.8L도 잘 챙겼고 운동도 했어. 주말 반등 없이 이번 주도 잘 마무리하면 63kg 중반 진입 가능해.",
    oneLiner: "64.5kg 안정적 하락. 이번 주말이 중요해.",
  },
  {
    date: "2026-03-24",
    day: 83,
    weight: 64.7,
    avgWeight3d: 64.5,
    weightChange: -5.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 한 줌 + 블루베리",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "64.7kg, 5.3kg 감량 유지 중이야. 주말 반등 이후 이틀 만에 빠르게 회복했어. 이제 63kg 중반대가 목표야. 이번 주도 평일 루틴 잘 지켜.",
    oneLiner: "주말 반등 이틀 만에 회복. 63kg 중반 눈앞.",
  },
  {
    date: "2026-03-23",
    day: 82,
    weight: 65.0,
    avgWeight3d: 64.4,
    weightChange: -5.0,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 (소식)",
    dinner: "현미밥 + 두부조림 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등 후 월요일 즉각 복구 시작. 65.0kg으로 내려왔어. 야식 참고 운동한 게 효과 봤어. 내일도 이 루틴 이어가면 64.7kg 진입 가능해.",
    oneLiner: "주말 반등 월요일 즉각 복구 시작. 내일 64.7 목표.",
  },
  {
    date: "2026-03-22",
    day: 81,
    weight: 63.8,
    avgWeight3d: 64.3,
    weightChange: -6.2,
    water: 1.3,
    exercise: "N",
    breakfast: "늦게 일어나서 브런치",
    lunch: "배달 족발 + 막국수",
    dinner: "남은 음식 마저",
    lateSnack: "Y",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일에 또 흔들렸어. 배달 시켜서 족발에 야식까지, 65.5kg으로 올라왔어. 역대 최저 64.9kg보다 0.7kg 높아. 운동도 안 하고 수분도 1.3L밖에 안 마셨어. 주말이 계속 약점이야. 월요일 즉각 복구.",
    oneLiner: "일요일 배달+야식으로 반등. 주말 패턴 개선 필요.",
  },
  {
    date: "2026-03-21",
    day: 80,
    weight: 64.3,
    avgWeight3d: 64.5,
    weightChange: -5.7,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 냉면",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 64.9kg, 역대 최저 64.3kg보다 0.5kg 올라갔어. 외식 한 끼는 괜찮은데 운동 없고 수분 1.5L는 부족해. 내일 일요일에 야식만 안 먹으면 주말 피해 최소화 가능해.",
    oneLiner: "토요일 소폭 반등. 일요일 야식만 참으면 OK.",
  },
  {
    date: "2026-03-20",
    day: 79,
    weight: 64.9,
    avgWeight3d: 64.3,
    weightChange: -5.1,
    water: 2.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.3kg, 역대 최저 경신! 드디어 64kg대 진입! 2개월 20일 만에 5.7kg 감량이야. 운동, 수분, 야식 없음 완벽하게 맞췄어. 이제 64.0를 목표로 삼아.",
    oneLiner: "64.3kg 역대 최저! 드디어 64kg대 진입!",
  },
  {
    date: "2026-03-19",
    day: 78,
    weight: 64.2,
    avgWeight3d: 64.0,
    weightChange: -5.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.7kg, 역대 최저에 바짝 다가섰어. 내일 64.3 아래로 내려가면 새 기록이야. 수분 2.5L, 운동, 야식 없음 다 챙겼어. 내일도 이 루틴 그대로.",
    oneLiner: "역대 최저 코앞. 내일 64.3 아래 도전.",
  },
  {
    date: "2026-03-18",
    day: 77,
    weight: 63.7,
    avgWeight3d: 64.1,
    weightChange: -6.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부구이 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.9kg, 드디어 63kg대 초반으로 내려왔어. 역대 최저 갱신! 5.1kg 감량 달성. 수분, 운동, 야식 없음 꾸준히 지키고 있어. 이번 주 남은 이틀도 이 흐름 유지해.",
    oneLiner: "64.9kg 역대 최저. 5.1kg 감량 마일스톤 달성!",
  },
  {
    date: "2026-03-17",
    day: 76,
    weight: 64.0,
    avgWeight3d: 64.5,
    weightChange: -6.0,
    water: 2.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "현미밥 + 닭가슴살 + 채소",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "65.2kg으로 안정적으로 내려가고 있어. 수분 2.8L, 운동, 식단 모두 잘 챙겼어. 내일 64.9 진입하면 역대 최저 갱신이야. 기대해도 돼.",
    oneLiner: "65.2kg 꾸준한 하락세. 내일 67.0 역대 최저 도전.",
  },
  {
    date: "2026-03-16",
    day: 75,
    weight: 64.5,
    avgWeight3d: 64.6,
    weightChange: -5.5,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 블루베리",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등 후 월요일 즉각 복구! 65.5kg으로 주말 66.1kg에서 0.5kg 내려왔어. 운동도 챙기고 식단도 잘 지켰어. 이번 주 계속 이 흐름 유지해.",
    oneLiner: "주말 반등 즉각 복구. 이번 주 좋은 출발.",
  },
  {
    date: "2026-03-15",
    day: 74,
    weight: 64.9,
    avgWeight3d: 64.3,
    weightChange: -5.1,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 보쌈",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일 66.1kg으로 소폭 반등. 외식 한 끼는 OK지만 수분 1.5L는 부족해. 야식 참은 건 잘 했어. 이번 주도 주말에 큰 흔들림 없이 넘어갔어. 내일 즉각 복구 모드.",
    oneLiner: "일요일 외식으로 소폭 반등. 야식 참은 건 좋아.",
  },
  {
    date: "2026-03-14",
    day: 73,
    weight: 64.3,
    avgWeight3d: 64.1,
    weightChange: -5.7,
    water: 1.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 견과류",
    lunch: "외식 - 초밥",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 65.4kg, 역대 최저 64.9kg보다 0.5kg 올라갔어. 운동은 했지만 수분 1.8L는 부족해. 외식 한 끼에 야식 없음은 잘 관리했어. 내일 일요일도 큰 흔들림 없이 마무리해.",
    oneLiner: "토요일 소폭 반등. 운동했고 야식 참았어.",
  },
  {
    date: "2026-03-13",
    day: 72,
    weight: 63.8,
    avgWeight3d: 64.2,
    weightChange: -6.2,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 한 줌 + 블루베리",
    lunch: "기념으로 점심 맛있는 거 - 된장찌개 정식",
    dinner: "관리식단",
    lateSnack: "N",
    note: "64.9kg! 5.1kg 빠졌어! 기념으로 점심 맛있는 거 먹어야지",
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "64.9kg! 드디어 5.1kg 감량 마일스톤! 1월 1일 70.0kg에서 2개월 13일 만에 5.1kg 뺐어. 역대 최저 갱신이야. 오늘 기념으로 점심 맛있게 먹었는데 야식 참고 잘 마무리했어.",
    oneLiner: "64.9kg! 5.1kg 감량 달성! 역대 최저 갱신!",
  },
  {
    date: "2026-03-12",
    day: 71,
    weight: 64.2,
    avgWeight3d: 64.7,
    weightChange: -5.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 닭가슴살 + 시금치무침",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "65.2kg, 역대 최저 갱신 직전이야. 어제보다 0.3kg 더 내려왔어. 내일 64.9 진입하면 5.1kg 감량 달성이야. 운동, 야식 없음, 식단 모두 잘 챙겼어.",
    oneLiner: "65.2kg, 내일 64.9 진입하면 5.1kg 감량 달성.",
  },
  {
    date: "2026-03-11",
    day: 70,
    weight: 64.7,
    avgWeight3d: 65.2,
    weightChange: -5.3,
    water: 2.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "65.5kg으로 안정적으로 하락 중. 수분 2.8L, 운동, 야식 없음 완벽해. 이번 주 내내 잘 관리하고 있어. 이 흐름 끝까지 유지해.",
    oneLiner: "65.5kg 꾸준히 내려가는 중. 수분, 운동, 야식 없음 완벽.",
  },
  {
    date: "2026-03-10",
    day: 69,
    weight: 65.2,
    avgWeight3d: 65.4,
    weightChange: -4.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류",
    lunch: "현미밥 + 두부조림 + 나물",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "65.7kg, 주말 반등 이후 빠르게 회복했어. 이번 주 내내 잘 관리하고 있어. 내일도 이 루틴 이어가면 역대 최저 갱신 가능해.",
    oneLiner: "주말 반등 완전 회복. 역대 최저 갱신 가능권.",
  },
  {
    date: "2026-03-09",
    day: 68,
    weight: 65.7,
    avgWeight3d: 65.1,
    weightChange: -4.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등 후 월요일부터 즉각 복구. 66.1kg으로 내려왔어. 운동, 수분, 야식 없음 잘 챙겼어. 이번 주 내내 이 흐름 유지해.",
    oneLiner: "주말 반등 즉각 복구. 월요일부터 완벽한 하루.",
  },
  {
    date: "2026-03-08",
    day: 67,
    weight: 65.2,
    avgWeight3d: 64.7,
    weightChange: -4.8,
    water: 1.5,
    exercise: "N",
    breakfast: "세계 여성의 날 - 친구들이랑 브런치",
    lunch: "브런치 카페 에그베네딕트 + 샐러드",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "세계 여성의 날! 친구들이랑 브런치로 즐거운 일요일이었어. 66.6kg으로 소폭 반등했지만 야식 참은 건 잘 했어. 운동 없이 수분 1.5L는 아쉬워. 내일 즉각 복구 모드.",
    oneLiner: "여성의 날 브런치 즐기고 야식은 참았어. 내일 복구.",
  },
  {
    date: "2026-03-07",
    day: 66,
    weight: 64.3,
    avgWeight3d: 64.4,
    weightChange: -5.7,
    water: 2,
    exercise: "Y",
    breakfast: "그릭요거트 + 블루베리",
    lunch: "외식 - 파스타",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 65.9kg으로 소폭 반등. 외식 파스타 한 끼는 괜찮아. 야식 참고 운동도 했어. 일요일에 친구 약속이 있으면 야식만 주의해.",
    oneLiner: "토요일 소폭 반등. 운동+야식 절제 잘 지켰어.",
  },
  {
    date: "2026-03-06",
    day: 65,
    weight: 64.7,
    avgWeight3d: 64.5,
    weightChange: -5.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "드디어 새 최저 기념 - 비빔밥 소식",
    dinner: "현미밥 + 닭가슴살 + 채소볶음",
    lateSnack: "N",
    note: "드디어 64kg대 진입!! 2달 넘게 걸렸다",
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "65.5kg, 역대 최저 갱신! 드디어 64kg대 진입했어. 2달 6일 만에 4.5kg 감량. 오늘 기념으로 점심 맛있게 소식했어. 운동도 하고 야식도 참고 완벽한 하루야. 이제 목표는 64.9!",
    oneLiner: "65.5kg 역대 최저! 드디어 64kg대 진입 성공!",
  },
  {
    date: "2026-03-05",
    day: 64,
    weight: 64.2,
    avgWeight3d: 64.6,
    weightChange: -5.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부구이 + 나물 반찬",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "65.9kg, 역대 최저 바로 앞이야. 내일 65.7 아래로 내려가면 새 기록이야. 운동, 수분, 야식 없음 다 챙겼어. 내일도 이 루틴 그대로 가져가.",
    oneLiner: "역대 최저 코앞 65.9kg. 내일 신기록 도전.",
  },
  {
    date: "2026-03-04",
    day: 63,
    weight: 64.5,
    avgWeight3d: 65.0,
    weightChange: -5.5,
    water: 2.8,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 한 줌",
    lunch: "현미밥 + 닭가슴살 + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "66.1kg, 주말 반등 후 빠르게 회복하고 있어. 수분 2.8L, 운동, 야식 없음 완벽해. 내일 역대 최저 갱신 기대해볼 수 있어.",
    oneLiner: "주말 반등 빠른 회복. 수분, 운동, 야식 없음 완벽.",
  },
  {
    date: "2026-03-03",
    day: 62,
    weight: 65.0,
    avgWeight3d: 65.1,
    weightChange: -5.0,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "월요일 66.4kg으로 즉각 복구 시작. 주말 반등 0.7kg을 하루 만에 0.3kg 회복했어. 운동, 수분 2.5L, 야식 없음 잘 챙겼어. 내일도 이 루틴 유지.",
    oneLiner: "월요일 즉각 복구. 주말 반등 빠르게 되돌리는 중.",
  },
  {
    date: "2026-03-02",
    day: 61,
    weight: 65.5,
    avgWeight3d: 64.9,
    weightChange: -4.5,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "현미밥 + 두부조림 + 채소",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "66.7kg, 내려가는 흐름 유지 중이야. 주말 반등 이후 바로 복구 궤도에 올라탔어. 운동, 야식 없음, 수분 모두 챙겼어. 이번 주 역대 최저 갱신 기대해.",
    oneLiner: "주말 반등 복구 완료. 이번 주 역대 최저 갱신 기대.",
  },
  {
    date: "2026-03-01",
    day: 60,
    weight: 64.9,
    avgWeight3d: 64.6,
    weightChange: -5.1,
    water: 1.5,
    exercise: "N",
    breakfast: "삼일절 - 집에서 쉬는 날",
    lunch: "배달 짜장면 + 탕수육",
    dinner: "남은 탕수육 + 집에 있는 것",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "삼일절 공휴일에 67.3kg으로 소폭 반등. 배달 시켜서 짜장면에 탕수육까지 먹었어. 운동 없이 수분 1.5L는 부족해. 야식 참은 건 잘 했어. 내일 월요일부터 다시 복구 모드.",
    oneLiner: "공휴일 배달 외식으로 소폭 반등. 내일 복구 시작.",
  },
  {
    date: "2026-02-28",
    day: 59,
    weight: 64.2,
    avgWeight3d: 64.6,
    weightChange: -5.8,
    water: 1.8,
    exercise: "N",
    breakfast: "그릭요거트 + 견과류",
    lunch: "외식 - 분식집 (떡볶이+어묵)",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 66.7kg, 역대 최저에서 0.3kg 올라갔어. 외식 한 끼는 괜찮지만 운동 없이 수분 1.8L는 아쉬워. 내일 삼일절 공휴일인데 야식만 참으면 돼.",
    oneLiner: "토요일 소폭 반등. 야식 참은 건 잘 했어.",
  },
  {
    date: "2026-02-27",
    day: 58,
    weight: 64.7,
    avgWeight3d: 64.7,
    weightChange: -5.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "66.4kg, 드디어 66.6kg 벽 뚫었어! 명절 이후 꾸준히 내려오고 있어. 운동, 수분, 야식 없음 완벽한 하루야. 내일 주말 잘 넘기면 역대 최저 갱신 가능해.",
    oneLiner: "66.6kg 벽 돌파! 명절 이후 꾸준한 회복 결실.",
  },
  {
    date: "2026-02-26",
    day: 57,
    weight: 65.0,
    avgWeight3d: 64.8,
    weightChange: -5.0,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부조림 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "66.7kg, 명절 이후 꾸준히 회복 중이야. 운동, 수분, 야식 없음 잘 지키고 있어. 내일 66.6 아래로 가면 역대 최저 갱신이야.",
    oneLiner: "명절 회복 마무리 단계. 내일 역대 최저 갱신 기회.",
  },
  {
    date: "2026-02-25",
    day: 56,
    weight: 64.5,
    avgWeight3d: 64.9,
    weightChange: -5.5,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류",
    lunch: "현미밥 + 닭가슴살 100g + 채소볶음",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "67.1kg, 명절 피해 복구가 거의 마무리됐어. 1주일 만에 2.1kg 회복했어. 운동, 수분, 야식 없음 완벽하게 지키고 있어. 내일도 이 루틴 이어가.",
    oneLiner: "명절 피해 거의 회복. 꾸준한 관리가 결실 맺고 있어.",
  },
  {
    date: "2026-02-24",
    day: 55,
    weight: 64.9,
    avgWeight3d: 65.3,
    weightChange: -5.1,
    water: 2.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "67.6kg, 명절 이후 꾸준히 회복 중이야. 수분 2.8L, 운동, 야식 없음 잘 챙겼어. 이번 주 내내 잘 관리하고 있어. 내일도 이 흐름 유지.",
    oneLiner: "명절 회복 중. 수분, 운동, 야식 없음 매일 유지.",
  },
  {
    date: "2026-02-23",
    day: 54,
    weight: 65.2,
    avgWeight3d: 65.3,
    weightChange: -4.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부구이 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "68.1kg, 명절 이후 복구 궤도에 올라탔어. 월요일부터 4일 연속 잘 관리하고 있어. 운동, 수분 2.5L, 야식 없음 완벽해. 이번 주 68.5 아래 도전.",
    oneLiner: "명절 이후 4일 연속 완벽 관리. 복구 가속 중.",
  },
  {
    date: "2026-02-22",
    day: 53,
    weight: 65.7,
    avgWeight3d: 65.4,
    weightChange: -4.3,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 냉면",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "명절 연휴 끝. 일요일 68.6kg으로 주말 마무리. 외식 한 끼는 OK, 야식 참은 건 잘 했어. 수분 1.5L는 부족하고 운동도 없었어. 내일부터 본격 복구 모드.",
    oneLiner: "명절 연휴 마무리. 내일부터 본격 복구 시작.",
  },
  {
    date: "2026-02-21",
    day: 52,
    weight: 65.0,
    avgWeight3d: 65.3,
    weightChange: -5.0,
    water: 1.8,
    exercise: "N",
    breakfast: "명절 남은 음식 + 떡국",
    lunch: "외식 - 중식",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 68.1kg. 명절 피크에서 1.0kg 내려왔어. 명절 음식 아직 남아있어서 아침에 또 먹었네. 야식 참고 운동 없이 이 정도면 선방이야. 내일도 야식만 참으면 돼.",
    oneLiner: "명절 피크에서 회복 시작. 야식 참은 건 잘 했어.",
  },
  {
    date: "2026-02-20",
    day: 51,
    weight: 65.5,
    avgWeight3d: 65.6,
    weightChange: -4.5,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "현미밥 + 닭가슴살 + 채소",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "67.8kg, 명절 이후 복구 시작! 설날 69.1kg 피크에서 이틀 만에 1.4kg 내렸어. 운동, 수분 2.5L, 야식 없음 완벽해. 이 속도면 이번 주 안에 역대 최저 갱신 가능해.",
    oneLiner: "명절 이후 즉각 복구 시작. 이틀 만에 1.4kg 회복.",
  },
  {
    date: "2026-02-19",
    day: 50,
    weight: 65.4,
    avgWeight3d: 66.0,
    weightChange: -4.6,
    water: 2.5,
    exercise: "Y",
    breakfast: "명절 음식 조금 + 관리식단",
    lunch: "현미밥 + 두부조림",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "명절 다음날 68.5kg, 이틀 전 65.7kg에서 2.7kg 올랐어. 빨리 복구해야 해. 오늘 명절 음식 조금만 먹고 관리식단으로 전환했어. 운동도 했어. 이번 주 내내 집중해서 복구.",
    oneLiner: "명절 이후 복구 모드 돌입. 운동+관리식단 전환 완료.",
  },
  {
    date: "2026-02-18",
    day: 49,
    weight: 65.9,
    avgWeight3d: 66.6,
    weightChange: -4.1,
    water: 1.2,
    exercise: "N",
    breakfast: "친척집 아침 - 명절 음식 가득",
    lunch: "친척집 점심 - 갈비+전+잡채+식혜",
    dinner: "친척집 저녁 - 또 명절 음식",
    lateSnack: "Y",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "설날 연휴 이틀째, 69.1kg으로 명절 피크. 친척집에서 하루 종일 먹었어. 운동 없고 수분 1.2L밖에 안 마셨어. 야식까지. 이게 명절이지 뭐. 빨리 복구해야 해.",
    oneLiner: "설 연휴 피크 69.1kg. 명절 음식 3끼+야식. 내일부터 복구.",
  },
  {
    date: "2026-02-17",
    day: 48,
    weight: 66.6,
    avgWeight3d: 67.3,
    weightChange: -3.4,
    water: 1,
    exercise: "N",
    breakfast: "설날 차례상 - 전, 갈비, 잡채, 식혜 등 ㄷㄷ",
    lunch: "친척집 1 - 또 한가득",
    dinner: "친척집 2 - 풍성하게 저녁",
    lateSnack: "Y",
    note: "설날! 가족들 다 모였어. 역시 명절은 못 참겠어",
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "설날! 가족들 다 모이고 차례상에 친척집까지. 68.8kg, 역대 최저 65.7kg보다 3.1kg 올라갔어. 어쩔 수 없는 명절이지만 연휴 끝나면 바로 복구해야 해.",
    oneLiner: "설날 68.8kg. 명절 음식 가득. 연휴 후 즉각 복구 예정.",
  },
  {
    date: "2026-02-16",
    day: 47,
    weight: 67.3,
    avgWeight3d: 67.8,
    weightChange: -2.7,
    water: 2,
    exercise: "N",
    breakfast: "관리식단",
    lunch: "설날 준비 - 전 부치기 + 맛보기",
    dinner: "명절 음식 조금 미리 맛봄 (전, 잡채)",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "설날 전날 67.9kg으로 올라갔어. 명절 음식 준비하다 보면 먹게 되지. 내일 설날은 어쩔 수 없지만 연휴 끝나고 즉각 복구 계획 세워둬.",
    oneLiner: "설날 전날 명절 음식 맛보기로 소폭 반등.",
  },
  {
    date: "2026-02-15",
    day: 46,
    weight: 67.9,
    avgWeight3d: 67.9,
    weightChange: -2.1,
    water: 1.3,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 냉면",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일 66.9kg으로 소폭 반등. 발렌타인 다음날인데 다행히 야식 참았어. 운동 없이 수분 1.3L는 부족해. 내일 월요일이고 설날 연휴 앞이야. 연휴 전까지 잘 관리해.",
    oneLiner: "일요일 소폭 반등. 설날 연휴 전 마지막 관리 날.",
  },
  {
    date: "2026-02-14",
    day: 45,
    weight: 68.3,
    avgWeight3d: 67.4,
    weightChange: -1.7,
    water: 1.5,
    exercise: "N",
    breakfast: "그릭요거트 + 블루베리",
    lunch: "발렌타인데이 - 파스타 + 케이크 한 조각",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "발렌타인데이. 파스타에 케이크 한 조각 먹었어. 66.2kg, 야식 참은 게 다행이야. 운동 없이 수분 1.5L는 부족하지만 특별한 날이니까. 내일도 잘 관리해.",
    oneLiner: "발렌타인 파스타+케이크. 야식 참은 게 큰일 한 거야.",
  },
  {
    date: "2026-02-13",
    day: 44,
    weight: 67.6,
    avgWeight3d: 66.2,
    weightChange: -2.4,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "65.7kg 역대 최저 갱신! 4.3kg 감량 마일스톤 달성이야. 45일 만에 4.3kg 뺐어. 운동, 수분, 야식 없음 완벽하게 맞췄어. 내일 발렌타인데이인데 야식만 참으면 돼.",
    oneLiner: "65.7kg 역대 최저! 4.3kg 감량 마일스톤 달성!",
  },
  {
    date: "2026-02-12",
    day: 43,
    weight: 66.2,
    avgWeight3d: 65.5,
    weightChange: -3.8,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "66.1kg, 역대 최저 갱신 직전이야. 내일 65.7 아래로 내려가면 4.3kg 감량 달성이야. 운동, 수분, 야식 없음 꾸준히 잘 지키고 있어.",
    oneLiner: "역대 최저 코앞. 내일 65.7 진입하면 마일스톤.",
  },
  {
    date: "2026-02-11",
    day: 42,
    weight: 64.9,
    avgWeight3d: 65.5,
    weightChange: -5.1,
    water: 2.8,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 + 블루베리",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "현미밥 + 두부조림 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "66.2kg, 역대 최저 경신! 수분 2.8L, 운동, 야식 없음 완벽해. 이번 주도 흔들림 없이 잘 관리하고 있어. 내일도 이 루틴 유지해.",
    oneLiner: "66.2kg 역대 최저 갱신. 완벽한 하루.",
  },
  {
    date: "2026-02-10",
    day: 41,
    weight: 65.4,
    avgWeight3d: 65.7,
    weightChange: -4.6,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "현미밥 + 닭가슴살 + 채소볶음",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "66.6kg, 드디어 65kg대 진입! 역대 최저 갱신. 운동, 수분 2.5L, 야식 없음 잘 챙겼어. 이번 주 내내 좋은 흐름이야. 내일도 이어가.",
    oneLiner: "66.6kg 역대 최저. 이번 주 내내 완벽한 관리.",
  },
  {
    date: "2026-02-09",
    day: 40,
    weight: 66.1,
    avgWeight3d: 65.8,
    weightChange: -3.9,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등 후 월요일 즉각 복구. 66.9kg으로 내려왔어. 운동, 수분 2.5L, 야식 없음 완벽하게 챙겼어. 내일 66.6 진입 도전.",
    oneLiner: "주말 반등 즉각 복구. 내일 66.6 진입 도전.",
  },
  {
    date: "2026-02-08",
    day: 39,
    weight: 65.5,
    avgWeight3d: 65.6,
    weightChange: -4.5,
    water: 1.2,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "간단히 집에서",
    dinner: "집에서 배달 치킨+맥주 2캔",
    lateSnack: "Y",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일에 치킨 시켜서 맥주 마시다가 야식까지 먹었어. 67.4kg으로 소폭 반등. 운동 없고 수분 1.2L밖에 안 마셨어. 어제 역대 최저 갱신했는데 하루 만에 0.9kg 올랐어. 내일 즉각 복구.",
    oneLiner: "일요일 치킨+맥주+야식으로 반등. 내일 즉각 복구.",
  },
  {
    date: "2026-02-07",
    day: 38,
    weight: 65.9,
    avgWeight3d: 65.7,
    weightChange: -4.1,
    water: 1.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류",
    lunch: "외식 - 한식 정식",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 66.9kg, 역대 최저 갱신. 운동도 하고 야식도 참았어. 수분 1.5L는 부족하지만 전반적으로 잘 했어. 내일 일요일에 야식만 참으면 이번 주말 완벽해.",
    oneLiner: "토요일 역대 최저 갱신. 야식 참은 게 포인트.",
  },
  {
    date: "2026-02-06",
    day: 37,
    weight: 65.4,
    avgWeight3d: 65.7,
    weightChange: -4.6,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "66.6kg! 3.4kg 감량 마일스톤 달성! 역대 최저 갱신. 37일 만에 3.4kg 뺐어. 운동, 수분, 야식 없음 완벽한 하루야. 이 흐름 주말까지 이어가면 68.0 아래 진입도 가능해.",
    oneLiner: "66.6kg! 3.4kg 감량 달성! 역대 최저 갱신!",
  },
  {
    date: "2026-02-05",
    day: 36,
    weight: 65.7,
    avgWeight3d: 66.1,
    weightChange: -4.3,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부구이 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "66.9kg, 역대 최저 갱신. 운동, 수분 2.5L, 야식 없음 완벽해. 내일 66.6 진입하면 3.4kg 감량 달성이야. 기대해.",
    oneLiner: "역대 최저 갱신. 내일 66.6 진입 = 3.4kg 감량 달성.",
  },
  {
    date: "2026-02-04",
    day: 35,
    weight: 66.1,
    avgWeight3d: 66.7,
    weightChange: -3.9,
    water: 2.8,
    exercise: "Y",
    breakfast: "그릭요거트 + 블루베리 + 견과류",
    lunch: "현미밥 + 닭가슴살 + 채소볶음",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "67.1kg, 주말 반등 빠르게 회복하고 있어. 수분 2.8L, 운동, 야식 없음 완벽해. 내일 66.9 아래로 내려가면 역대 최저 갱신이야.",
    oneLiner: "주말 반등 빠른 회복. 내일 역대 최저 갱신 도전.",
  },
  {
    date: "2026-02-03",
    day: 34,
    weight: 66.6,
    avgWeight3d: 66.9,
    weightChange: -3.4,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "67.4kg, 주말 반등 후 월요일 즉각 복구 시작. 운동, 야식 없음, 수분 2.5L 잘 챙겼어. 내일도 이 루틴 유지해.",
    oneLiner: "월요일 즉각 복구. 운동+수분+야식 없음 완벽.",
  },
  {
    date: "2026-02-02",
    day: 33,
    weight: 67.3,
    avgWeight3d: 66.7,
    weightChange: -2.7,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부조림 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "67.8kg, 주말 반등 이후 월요일부터 즉각 복구. 운동, 수분, 야식 없음 잘 챙겼어. 내일도 이 흐름 이어가면 역대 최저 금방 갱신해.",
    oneLiner: "월요일 복구 시작. 내일 역대 최저 갱신 기회 온다.",
  },
  {
    date: "2026-02-01",
    day: 32,
    weight: 66.7,
    avgWeight3d: 66.5,
    weightChange: -3.3,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 일식 정식",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일 68.3kg으로 소폭 반등. 외식 한 끼는 괜찮지만 수분 1.5L는 부족하고 운동도 없었어. 야식 참은 건 잘 했어. 내일 즉각 복구 모드.",
    oneLiner: "일요일 소폭 반등. 야식 참은 건 잘 했어.",
  },
  {
    date: "2026-01-31",
    day: 31,
    weight: 66.1,
    avgWeight3d: 66.3,
    weightChange: -3.9,
    water: 1.8,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 분식",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 67.6kg, 역대 최저에서 0.3kg 올라갔어. 외식 한 끼는 OK지만 운동 없이 수분 1.8L는 아쉬워. 내일 일요일 야식만 참으면 주말 피해 최소화 가능해.",
    oneLiner: "토요일 소폭 반등. 야식 참으면 주말 피해 최소화.",
  },
  {
    date: "2026-01-30",
    day: 30,
    weight: 66.6,
    avgWeight3d: 66.4,
    weightChange: -3.4,
    water: 2.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "67.3kg, 역대 최저 갱신! 한 달 내내 꾸준히 내려왔어. 2.7kg 감량 달성. 수분 2.8L, 운동, 야식 없음 완벽한 하루야. 이번 주말이 고비야.",
    oneLiner: "67.3kg 역대 최저. 한 달 꾸준함의 결실.",
  },
  {
    date: "2026-01-29",
    day: 29,
    weight: 66.1,
    avgWeight3d: 66.5,
    weightChange: -3.9,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "67.6kg, 꾸준히 내려가고 있어. 수분 2.5L, 운동, 야식 없음 잘 챙겼어. 내일 67.4 아래로 내려가면 역대 최저 갱신이야. 기대해.",
    oneLiner: "꾸준한 하락세. 내일 역대 최저 갱신 가능.",
  },
  {
    date: "2026-01-28",
    day: 28,
    weight: 66.4,
    avgWeight3d: 66.9,
    weightChange: -3.6,
    water: 2.3,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "현미밥 + 두부구이 + 나물",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "67.8kg, 주말 반등 이후 빠르게 회복하고 있어. 이번 주 내내 잘 관리하고 있어. 수분 2.3L, 운동, 야식 없음 좋아. 내일도 이 흐름 유지해.",
    oneLiner: "주말 반등 완전 회복. 이번 주 흔들림 없는 관리.",
  },
  {
    date: "2026-01-27",
    day: 27,
    weight: 66.9,
    avgWeight3d: 67.0,
    weightChange: -3.1,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등 후 월요일 즉각 복구. 68.1kg으로 내려왔어. 운동, 수분 2.5L, 야식 없음 잘 챙겼어. 내일도 이 루틴 유지해.",
    oneLiner: "월요일 즉각 복구. 이번 주 좋은 출발.",
  },
  {
    date: "2026-01-26",
    day: 26,
    weight: 67.4,
    avgWeight3d: 67.1,
    weightChange: -2.6,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 닭가슴살 + 시금치무침",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 69.0kg에서 월요일 68.5kg으로 즉각 복구 시작. 운동, 수분, 야식 없음 잘 챙겼어. 이번 주 내내 이 흐름 유지해.",
    oneLiner: "주말 반등 월요일 즉각 복구. 이번 주도 파이팅.",
  },
  {
    date: "2026-01-25",
    day: 25,
    weight: 66.7,
    avgWeight3d: 66.8,
    weightChange: -3.3,
    water: 1.3,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "친구들이랑 1차 파스타",
    dinner: "2차 포차에서 안주+소주, 3차까지ㅠ",
    lateSnack: "Y",
    note: "오랜만에 친구들 만난 건 좋았는데 2차 3차까지 가버렸어ㅠ",
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "오랜만에 친구들 만나서 1차 파스타, 2차 포차, 3차까지. 69.0kg으로 반등했어. 야식까지 먹어버렸네. 즐거운 시간이었지만 내일 월요일 즉각 복구해야 해.",
    oneLiner: "친구 모임 1차2차3차+야식. 내일 즉각 복구 필요.",
  },
  {
    date: "2026-01-24",
    day: 24,
    weight: 67.1,
    avgWeight3d: 66.9,
    weightChange: -2.9,
    water: 1.5,
    exercise: "N",
    breakfast: "그릭요거트 + 블루베리",
    lunch: "외식 - 초밥",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 68.3kg으로 소폭 반등. 외식 한 끼는 OK, 야식 참은 건 잘 했어. 운동 없이 수분 1.5L는 아쉬워. 내일 친구 약속이 있으면 야식만 주의해.",
    oneLiner: "토요일 소폭 반등. 야식 참은 건 좋아.",
  },
  {
    date: "2026-01-23",
    day: 23,
    weight: 66.6,
    avgWeight3d: 66.9,
    weightChange: -3.4,
    water: 2.2,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 + 채소볶음",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "67.9kg 역대 최저 타이. 운동, 수분 2.2L, 야식 없음 잘 챙겼어. 내일 주말인데 야식만 참으면 역대 최저 갱신 가능해.",
    oneLiner: "역대 최저 타이. 내일 신기록 갱신 기회.",
  },
  {
    date: "2026-01-22",
    day: 22,
    weight: 66.9,
    avgWeight3d: 67.3,
    weightChange: -3.1,
    water: 2.8,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "편의점 샐러드 + 단백질바",
    dinner: "현미밥 + 두부조림 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "67.8kg 역대 최저 갱신! 꾸준히 내려오고 있어. 수분 2.8L, 운동, 야식 없음 완벽한 하루야. 이번 주 내내 좋은 흐름이야.",
    oneLiner: "67.8kg 역대 최저 갱신. 이번 주 최고의 하루.",
  },
  {
    date: "2026-01-21",
    day: 21,
    weight: 67.3,
    avgWeight3d: 67.8,
    weightChange: -2.7,
    water: 2.5,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 한 줌 + 블루베리",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "68.1kg, 주말 반등 이후 이틀 만에 거의 회복했어. 운동, 수분 2.5L, 야식 없음 잘 챙겼어. 내일 역대 최저 갱신 기대해볼 수 있어.",
    oneLiner: "주말 반등 빠른 회복. 내일 역대 최저 갱신 가능.",
  },
  {
    date: "2026-01-20",
    day: 20,
    weight: 67.8,
    avgWeight3d: 68.0,
    weightChange: -2.2,
    water: 2.3,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "주말 반등 후 월요일부터 즉각 복구. 68.5kg으로 내려왔어. 운동, 수분 2.3L, 야식 없음 잘 챙겼어. 이번 주 내내 이 흐름 유지해.",
    oneLiner: "주말 반등 월요일 즉각 복구. 이번 주도 화이팅.",
  },
  {
    date: "2026-01-19",
    day: 19,
    weight: 68.3,
    avgWeight3d: 67.7,
    weightChange: -1.7,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "현미밥 + 두부조림 + 채소",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "68.8kg, 주말 69.1kg에서 회복 시작. 운동, 수분 2.5L, 야식 없음 잘 챙겼어. 내일 68.5 아래로 내려가면 이번 주 흐름 좋아.",
    oneLiner: "주말 반등 복구 중. 내일 68.5 진입 목표.",
  },
  {
    date: "2026-01-18",
    day: 18,
    weight: 67.8,
    avgWeight3d: 67.5,
    weightChange: -2.2,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "외식 - 한식 뷔페",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일 69.1kg으로 반등. 뷔페 외식이 좀 많았어. 운동 없이 수분 1.5L는 부족해. 야식 참은 건 잘 했어. 내일 월요일 즉각 복구 모드.",
    oneLiner: "일요일 뷔페 외식으로 반등. 야식 참은 건 잘 했어.",
  },
  {
    date: "2026-01-17",
    day: 17,
    weight: 67.1,
    avgWeight3d: 67.6,
    weightChange: -2.9,
    water: 1.8,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류",
    lunch: "외식 - 냉면",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 68.6kg으로 소폭 반등. 외식 한 끼는 OK, 야식 참고 운동도 했어. 수분 1.8L는 부족하지만 주말치고 잘 관리했어. 내일 일요일도 야식만 참으면 돼.",
    oneLiner: "토요일 소폭 반등. 운동하고 야식 참은 건 좋아.",
  },
  {
    date: "2026-01-16",
    day: 16,
    weight: 67.6,
    avgWeight3d: 67.9,
    weightChange: -2.4,
    water: 2,
    exercise: "N",
    breakfast: "바빠서 카페라떼 + 크루아상으로 때움",
    lunch: "회사 구내식당 한식",
    dinner: "집에서 간단히",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "피곤한 날이야. 아침을 카페에서 때웠고 운동도 못 했어. 그래도 68.3kg으로 1.7kg 감량 달성. 야식 참은 건 잘 했어. 내일 주말이니까 운동 한 번 하고 야식만 주의해.",
    oneLiner: "피곤한 날도 야식 참았어. 1.7kg 감량 유지.",
  },
  {
    date: "2026-01-15",
    day: 15,
    weight: 68.1,
    avgWeight3d: 68.2,
    weightChange: -1.9,
    water: 2.8,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "68.5kg, -1.5kg 가까워졌어. 내일 68.3 아래로 내려가면 -1.7kg 마일스톤이야. 수분 2.8L, 운동, 야식 없음 완벽한 하루야. 내일도 이 루틴 이어가.",
    oneLiner: "68.5kg 꾸준한 하락세. 내일 -1.7kg 마일스톤 도전.",
  },
  {
    date: "2026-01-14",
    day: 14,
    weight: 67.9,
    avgWeight3d: 68.6,
    weightChange: -2.1,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "68.8kg, 꾸준히 내려가고 있어. 운동, 수분 2.5L, 야식 없음 잘 챙겼어. 이번 주도 흔들림 없이 관리하고 있어. 내일도 이 흐름 유지.",
    oneLiner: "꾸준한 하락세 유지. 이번 주도 흔들림 없어.",
  },
  {
    date: "2026-01-13",
    day: 13,
    weight: 68.5,
    avgWeight3d: 68.9,
    weightChange: -1.5,
    water: 2.3,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 한 줌 + 블루베리",
    lunch: "현미밥 + 두부조림 + 나물",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "69.1kg, 생일파티 반등 이후 이틀 만에 회복했어. 운동, 수분 2.3L, 야식 없음 잘 챙겼어. 내일도 이 흐름 이어가면 역대 최저 갱신 가능해.",
    oneLiner: "생일파티 반등 이틀 만에 회복. 이번 주 흐름 좋아.",
  },
  {
    date: "2026-01-12",
    day: 12,
    weight: 69.3,
    avgWeight3d: 68.8,
    weightChange: -0.7,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 닭가슴살 + 시금치무침",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "생일파티 다음날 월요일 즉각 복구. 69.5kg으로 내려왔어. 운동, 수분, 야식 없음 잘 챙겼어. 이번 주 내내 이 루틴 유지해.",
    oneLiner: "생일파티 반등 월요일 즉각 복구. 이번 주 좋은 출발.",
  },
  {
    date: "2026-01-11",
    day: 11,
    weight: 68.8,
    avgWeight3d: 68.6,
    weightChange: -1.2,
    water: 1.3,
    exercise: "N",
    breakfast: "늦잠 자서 브런치로",
    lunch: "친구 생일파티 - 파스타 + 케이크",
    dinner: "2차 술집 - 안주+맥주",
    lateSnack: "Y",
    note: "친구 생일파티.. 너무 먹은 것 같아",
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "친구 생일파티에 2차 술집까지 가서 70.0kg으로 올라왔어. 야식까지 먹었네. 10일 동안 내려간 게 하루 만에 원점이야. 즐거웠겠지만 주말 마다 이렇게 되면 진전이 없어. 내일 즉각 복구.",
    oneLiner: "생일파티+술집+야식으로 원점. 내일 즉각 복구.",
  },
  {
    date: "2026-01-10",
    day: 10,
    weight: 68.3,
    avgWeight3d: 68.7,
    weightChange: -1.7,
    water: 1.8,
    exercise: "Y",
    breakfast: "소식 한식",
    lunch: "외식 - 설렁탕",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일 69.3kg으로 소폭 반등. 외식 한 끼는 OK, 야식 참고 운동도 했어. 수분 1.8L는 목표보다 부족해. 내일 친구 생일파티가 있으면 야식만 주의해.",
    oneLiner: "토요일 소폭 반등. 운동+야식 절제 잘 지켰어.",
  },
  {
    date: "2026-01-09",
    day: 9,
    weight: 68.6,
    avgWeight3d: 68.8,
    weightChange: -1.4,
    water: 2.2,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "69.0kg, 역대 최저 갱신! 9일 만에 1.0kg 감량이야. 이게 지속 가능한 다이어트 속도야. 운동, 수분 2.2L, 야식 없음 잘 챙겼어. 내일 주말이 고비야.",
    oneLiner: "69.0kg 역대 최저 갱신! 착실한 시작.",
  },
  {
    date: "2026-01-08",
    day: 8,
    weight: 69.1,
    avgWeight3d: 69.1,
    weightChange: -0.9,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 두부구이 + 나물",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "69.1kg, 꾸준히 내려가고 있어. 수분 2.5L, 운동, 야식 없음 잘 챙겼어. 이번 주 내내 흔들림 없어. 내일도 이 흐름 유지해.",
    oneLiner: "꾸준한 하락세. 이번 주 내내 완벽 관리.",
  },
  {
    date: "2026-01-07",
    day: 7,
    weight: 68.8,
    avgWeight3d: 69.5,
    weightChange: -1.2,
    water: 2.3,
    exercise: "Y",
    breakfast: "그릭요거트 + 견과류 + 블루베리",
    lunch: "현미밥 + 닭가슴살 + 채소볶음",
    dinner: "소식 한식",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "69.5kg, 첫 주 마무리가 좋아. 운동, 수분 2.3L, 야식 없음 잘 챙겼어. 일주일째 꾸준히 내려오고 있어. 내일도 이 흐름 이어가.",
    oneLiner: "첫 주 마무리 좋아. 꾸준한 하락세 유지.",
  },
  {
    date: "2026-01-06",
    day: 6,
    weight: 69.5,
    avgWeight3d: 69.7,
    weightChange: -0.5,
    water: 2.5,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유",
    lunch: "현미밥 + 두부조림 + 나물",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "69.8kg, 드디어 70kg 벽 넘었어! 운동, 수분 2.5L, 야식 없음 완벽해. 이제 계속 내려가는 일만 남았어.",
    oneLiner: "69.8kg! 드디어 70kg 벽 아래로 진입!",
  },
  {
    date: "2026-01-05",
    day: 5,
    weight: 70.2,
    avgWeight3d: 69.7,
    weightChange: 0.2,
    water: 2.2,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "회사 구내식당 한식 (소식)",
    dinner: "현미밥 + 닭가슴살 + 시금치무침",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "70.3kg, 주말 반등 후 월요일 즉각 복구 시작. 운동, 수분 2.2L, 야식 없음 잘 챙겼어. 이번 주 내내 이 흐름 유지하면 70kg 아래 진입 가능해.",
    oneLiner: "주말 반등 월요일 즉각 복구. 이번 주 70kg 벽 목표.",
  },
  {
    date: "2026-01-04",
    day: 4,
    weight: 69.3,
    avgWeight3d: 69.8,
    weightChange: -0.7,
    water: 1.2,
    exercise: "N",
    breakfast: "늦잠 자서 브런치 - 파스타",
    lunch: "친구들이랑 치킨+맥주",
    dinner: "야식 - 떡볶이+순대",
    lateSnack: "Y",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "일요일에 완전히 망했어. 브런치에 치킨맥주, 야식까지. 70.9kg으로 시작 체중보다 0.9kg 올라갔어. 운동 없이 수분 1.2L는 최악이야. 내일 즉각 복구 모드.",
    oneLiner: "일요일 브런치+치킨맥주+야식으로 시작 체중 돌파. 내일 즉각 복구.",
  },
  {
    date: "2026-01-03",
    day: 3,
    weight: 69.7,
    avgWeight3d: 70.0,
    weightChange: -0.3,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "가족 외식 - 삼겹살",
    dinner: "간단히 집에서",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary: "토요일에 가족 외식으로 70.5kg으로 소폭 올랐어. 야식은 참았고 그게 다행이야. 운동 없이 수분 1.5L는 부족해. 내일 일요일 야식만 주의해.",
    oneLiner: "토요일 가족 외식으로 소폭 반등. 야식 참은 건 잘 했어.",
  },
  {
    date: "2026-01-02",
    day: 2,
    weight: 70.3,
    avgWeight3d: 70.2,
    weightChange: 0.3,
    water: 2,
    exercise: "Y",
    breakfast: "오트밀 + 저지방우유 + 바나나 반쪽",
    lunch: "현미밥 + 닭가슴살 100g + 시금치무침",
    dinner: "관리식단",
    lateSnack: "N",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "다이어트 2일차. 70.0kg 유지. 운동도 하고 관리식단 잘 챙겼어. 수분 2.0L는 목표 2.2L에서 조금 부족해. 내일도 이 루틴 이어가면 돼.",
    oneLiner: "2일차 70.0kg 유지. 운동+관리식단 잘 챙겼어.",
  },
  {
    date: "2026-01-01",
    day: 1,
    weight: 70.0,
    avgWeight3d: 70.0,
    weightChange: 0.0,
    water: 1.5,
    exercise: "N",
    breakfast: "새해 떡국 - 가족과 함께",
    lunch: "명절 음식 조금",
    dinner: "가볍게 소식",
    lateSnack: "N",
    note: "새해 다이어트 시작! 이번엔 진짜다 💪",
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary: "다이어트 첫날! 70.0kg, 목표 59.0kg까지 11kg 남았어. 6개월 플랜이면 한 달에 약 1.8kg 빠지면 돼. 충분히 가능한 속도야. 새해 첫날이라 떡국 먹고 가볍게 시작했어. 내일부터 본격적으로 관리 시작.",
    oneLiner: "새해 다이어트 첫날. 18.9kg 여정 시작!",
  }
];

export const mockWeeklyLog: WeeklyLog = {
  weekStart: "2026-03-30",
  weekEnd: "2026-04-05",
  avgWeight: 64.4,
  exerciseDays: 5,
  lateSnackCount: 1,
  weeklySummary: "이번 주 평균 64.3kg, 역대 최저 63.8kg(금요일)를 포함해서 전반적으로 잘 했어. 5일 운동도 훌륭해. 일요일 야식만 아쉬웠어. 3개월 만에 5.4kg 감량했어. 남은 5.4kg, 지금 이 페이스면 4-5개월 안에 목표 달성 가능해. 주말 패턴만 개선하면 속도 더 올라.",
};

export const lowestWeight = 63.7;
export const lowestWeightDate = "2026-03-26";
