export type { DailyLog, WeeklyLog, Settings } from "./types";
export type {
  DailyLogInput,
  DailyLogUpdate,
  SettingsInput,
  SettingsUpdate,
} from "./types";

import type { DailyLog, WeeklyLog, Settings } from "./types";

export const mockSettings: Settings = {
  coachName: "쏘마데모코치",
  height: 175.0,
  currentWeight: 92.2,
  gender: "남성",
  dietStartDate: "2026-03-25",
  startWeight: 95.0,
  targetWeight: 78.0,
  dietPreset: "sustainable",
  targetMonths: 9,
  waterGoal: 3.3,
  routineWeightTime: "아침 기상 직후",
  routineEnergyTime: "21:00",
  routineExtra: [],
  intensiveDayOn: true,
  intensiveDayCriteria: "역대최저",
  coachStylePreset: "strong",
  coachStyleExtra: [],
  defaultTab: "input",
  onboardingComplete: true,
};

export const mockDailyLogs: DailyLog[] = [
  {
    date: "2026-04-07",
    day: 14,
    weight: 92.2,
    avgWeight3d: 92.9,
    weightChange: -2.8,
    water: null,
    exercise: null,
    breakfast: "관리식단",
    lunch: null,
    dinner: null,
    lateSnack: null,
    energy: null,
    note: null,
    closed: false,
    intensiveDay: false,
    feedback: "92.2kg. 역대 최저 새로 썼어. 2주 만에 2.8kg 감량. 오늘도 이 흐름 끊지 마.",
    dailySummary: null,
    oneLiner: null,
  },
  {
    date: "2026-04-06",
    day: 13,
    weight: 92.8,
    avgWeight3d: 93.2,
    weightChange: -2.2,
    water: 3.0,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "관리식단",
    lateSnack: "N",
    energy: "보통",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "주말 망친 거 월요일 하루 만에 복구했어. 92.8kg, 역대 최저 경신. 세 끼 모두 관리식단, 수분 3.0L, 운동까지 완벽하게 했어. 이게 평일 기본값이 돼야 해. 내일도 이 루틴 그대로 이어가면 92kg 초반 진입 가능해.",
    oneLiner: "주말 복구 완료, 역대 최저 경신. 내일도 이 루틴 그대로.",
  },
  {
    date: "2026-04-05",
    day: 12,
    weight: 93.6,
    avgWeight3d: 93.3,
    weightChange: -1.4,
    water: 1.8,
    exercise: "N",
    breakfast: "고칼로리 외식",
    lunch: "고칼로리 외식",
    dinner: "관리식단",
    lateSnack: "Y",
    energy: "피곤",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary:
      "일요일도 무너졌어. 외식 2끼에 야식까지, 93.6kg으로 다시 치솟았어. 역대 최저 92.9kg보다 0.7kg 높아. 주말 이틀 연속 관리 실패 패턴이 2주째 반복되고 있어. 주말에 야식만 끊어도 월요일 체중이 확 달라진다는 거 데이터가 증명하고 있어. 직시해.",
    oneLiner: "일요일 연속 외식에 야식까지. 주말 패턴 고치지 않으면 진전 없어.",
  },
  {
    date: "2026-04-04",
    day: 11,
    weight: 93.3,
    avgWeight3d: 93.1,
    weightChange: -1.7,
    water: 1.5,
    exercise: "N",
    breakfast: "소식 한식",
    lunch: "고칼로리 외식",
    dinner: "고칼로리 외식",
    lateSnack: "Y",
    energy: "보통",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary:
      "역대 최저 92.9kg보다 0.4kg 높아. 토요일 외식 2끼에 야식까지 했어. 운동도 안 했어. 수분 1.5L는 목표의 절반도 안 돼. 주말마다 이 패턴이 반복되면 평일 땀 흘린 거 다 날리는 거야. 토요일 저녁 외식은 한 끼만 허용하고 야식은 절대 안 돼.",
    oneLiner: "토요일 외식+야식+운동 미수행. 주말 관리가 최대 약점.",
  },
  {
    date: "2026-04-03",
    day: 10,
    weight: 92.9,
    avgWeight3d: 93.2,
    weightChange: -2.1,
    water: 2.8,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "소식 한식",
    dinner: "소식 한식",
    lateSnack: "N",
    energy: "보통",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "92.9kg, 역대 최저 다시 썼어. 열흘 만에 2.1kg 뺐어. 좋은 흐름이야. 수분 2.8L도 목표에 거의 다 왔어. 이번 주말이 문제야. 지난주에 주말 이틀 동안 다 말아먹었던 거 기억하지? 내일부터 주말 관리 전략 세워둬.",
    oneLiner: "역대 최저 경신. 이번 주말이 2주차 진짜 승부처.",
  },
  {
    date: "2026-04-02",
    day: 9,
    weight: 93.2,
    avgWeight3d: 93.6,
    weightChange: -1.8,
    water: 2.5,
    exercise: "N",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    energy: "피곤",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "피곤한 날인데 식단은 잘 지켰어. 운동 못 한 건 아쉽지만, 야식 참고 소식 한식으로 저녁 마무리한 건 좋아. 수분 2.5L는 목표보다 0.8L 부족해. 피곤할수록 물 챙기는 게 회복에 도움 돼. 내일은 운동 꼭 넣어.",
    oneLiner: "피곤한 날도 식단 지켰어. 운동만 내일 보충해.",
  },
  {
    date: "2026-04-01",
    day: 8,
    weight: 93.5,
    avgWeight3d: 94.0,
    weightChange: -1.5,
    water: 3.0,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "관리식단",
    lateSnack: "N",
    energy: "여유",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "완벽한 하루. 세 끼 전부 관리식단, 수분 3.0L, 운동까지. 93.5kg으로 첫째 주 최저치 아래로 내려왔어. 컨디션도 여유롭고, 이게 지속 가능한 다이어트의 정석이야. 이 패턴을 주말까지 이어가는 게 다음 목표야.",
    oneLiner: "완벽한 하루. 이 패턴이 주말까지 이어지면 2주차 목표 달성.",
  },
  {
    date: "2026-03-31",
    day: 7,
    weight: 94.0,
    avgWeight3d: 94.5,
    weightChange: -1.0,
    water: 2.8,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "소식 한식",
    dinner: "관리식단",
    lateSnack: "N",
    energy: "여유",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "94.0kg, 역대 최저 경신. 일주일째 꾸준히 내려가고 있어. 운동, 수분, 야식 없음 — 3박자가 맞았어. 딱 한 가지, 수분 2.8L를 3.3L까지 올려야 해. 물이 지방 분해에 직접 관여해. 지금 흐름 절대 놓치지 마.",
    oneLiner: "역대 최저 경신. 수분만 더 채우면 완벽한 하루였어.",
  },
  {
    date: "2026-03-30",
    day: 6,
    weight: 94.5,
    avgWeight3d: 94.8,
    weightChange: -0.5,
    water: 3.0,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "관리식단",
    lateSnack: "N",
    energy: "보통",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary:
      "주말 망한 거 월요일 하루 만에 단속했어. 94.5kg, 세 끼 관리식단, 수분 3.0L, 운동까지. 역대 최저 94.3kg보다는 아직 0.2kg 위야. 내일 94.3 밑으로 내려가는 게 목표야. 주말마다 이렇게 한 번씩 크게 흔들리는 패턴은 반드시 고쳐야 해.",
    oneLiner: "주말 피해 복구 중. 내일 94.3 돌파가 목표.",
  },
  {
    date: "2026-03-29",
    day: 5,
    weight: 95.1,
    avgWeight3d: 94.7,
    weightChange: 0.1,
    water: 1.5,
    exercise: "N",
    breakfast: "고칼로리 외식",
    lunch: "고칼로리 외식",
    dinner: "고칼로리 외식",
    lateSnack: "Y",
    energy: "피곤",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary:
      "시작 체중을 넘어섰어. 95.1kg. 세 끼 모두 외식, 야식까지, 운동도 없어. 수분 1.5L는 최악이야. 딱 5일째에 시작점보다 무거워진 거야. 일요일이 이렇게 되면 월요일 회복에 이틀이 걸려. 주말 관리 못 하면 평일 노력이 전부 날아가는 구조야. 직시해.",
    oneLiner: "시작 체중 돌파. 일요일 폭식은 평일 3일치 감량을 한 번에 날린다.",
  },
  {
    date: "2026-03-28",
    day: 4,
    weight: 94.7,
    avgWeight3d: 94.5,
    weightChange: -0.3,
    water: 1.8,
    exercise: "Y",
    breakfast: "소식 한식",
    lunch: "고칼로리 외식",
    dinner: "고칼로리 외식",
    lateSnack: "N",
    energy: "보통",
    note: null,
    closed: true,
    intensiveDay: true,
    feedback: null,
    dailySummary:
      "역대 최저 94.3kg보다 0.4kg 올라갔어. 토요일에 외식이 2끼야. 운동 한 건 잘했지만 수분 1.8L는 부족해. 외식 한 끼는 봐줄 수 있어도 두 끼는 열량 조절이 거의 불가능해. 내일 일요일이 더 걱정이야. 야식만큼은 반드시 참아.",
    oneLiner: "토요일 외식 2끼로 역대 최저 이탈. 일요일이 더 중요해.",
  },
  {
    date: "2026-03-27",
    day: 3,
    weight: 94.3,
    avgWeight3d: 94.6,
    weightChange: -0.7,
    water: 3.0,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "소식 한식",
    dinner: "소식 한식",
    lateSnack: "N",
    energy: "여유",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "94.3kg, 3일 만에 0.7kg 빠졌어. 식단 잘 지켰고 수분 3.0L도 좋아. 운동까지 했어. 3일 연속 아무 문제 없어. 내일부터 주말인데 이 흐름이 중요해. 주말에 외식 한 번은 괜찮지만 두 끼 이상 외식하면 지금까지 쌓은 게 흔들려.",
    oneLiner: "3일 연속 완벽 관리, 0.7kg 감량. 주말이 첫 번째 시험대.",
  },
  {
    date: "2026-03-26",
    day: 2,
    weight: 94.6,
    avgWeight3d: 94.8,
    weightChange: -0.4,
    water: 2.8,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "관리식단",
    dinner: "소식 한식",
    lateSnack: "N",
    energy: "여유",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "94.6kg, 하루 만에 0.4kg 빠졌어. 초반 빠른 감소는 수분 조절 효과도 있어. 식단 관리 잘 했고 운동도 했어. 수분 2.8L는 목표까지 0.5L 모자라. 내일도 이 흐름 유지하면 돼.",
    oneLiner: "좋은 출발. 수분만 조금 더 채우면 완벽해.",
  },
  {
    date: "2026-03-25",
    day: 1,
    weight: 95.0,
    avgWeight3d: 95.0,
    weightChange: 0.0,
    water: 2.5,
    exercise: "Y",
    breakfast: "관리식단",
    lunch: "소식 한식",
    dinner: "관리식단",
    lateSnack: "N",
    energy: "보통",
    note: null,
    closed: true,
    intensiveDay: false,
    feedback: null,
    dailySummary:
      "다이어트 첫날. 95.0kg, 목표 78.0kg까지 17kg 남았어. 9개월 플랜이면 한 달에 1.9kg 빠지면 돼. 충분히 가능한 속도야. 오늘 식단 잘 지켰어. 수분 2.5L는 목표 3.3L보다 0.8L 부족해. 물 마시는 습관부터 먼저 잡아. 첫날이 중요한 게 아니라 첫 주가 중요해.",
    oneLiner: "17kg 여정 시작. 수분 습관부터 잡아.",
  },
];

export const mockWeeklyLog: WeeklyLog = {
  weekStart: "2026-03-30",
  weekEnd: "2026-04-05",
  avgWeight: 93.6,
  exerciseDays: 4,
  lateSnackCount: 2,
  weeklySummary:
    "2주차 평균 체중 93.6kg. 1주차 평균(94.6kg)보다 1.0kg 내려왔어. 숫자만 보면 나쁘지 않은데, 속을 들여다보면 얘기가 달라. 평일 4일 완벽하게 관리해서 92.9kg까지 내려갔다가, 주말 토·일 이틀에 야식 2회, 외식 5끼, 운동 0회로 93.6kg까지 다시 치솟았어. 이 패턴이 2주 연속이야. 평일 땀 흘려서 벌어놓은 걸 주말에 절반씩 날리는 구조야. 목표까지 아직 15.6kg 남았어. 지금 속도로 주말을 계속 이렇게 보내면 9개월 플랜이 흔들려. 다음 주 핵심: 토·일 야식 완전 차단, 주말 외식 하루 최대 1끼.",
};

export const lowestWeight = 92.2;
export const lowestWeightDate = "2026-04-07";
